version: '3.8'

services:
  sniffer:
    build: .
    container_name: sniffer
    privileged: true
    network_mode: host
    volumes:
      - ./stats:/app/stats
    command: ["enp0s3"]
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./stats:/app/stats:ro
    environment:
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORG=myorg
      - INFLUXDB_BUCKET=packet-stats
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - app-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: packet-stats
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - app-network

  grafana-1:
    image: grafana/grafana:latest
    container_name: grafana-1
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data-1:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app-network

  grafana-2:
    image: grafana/grafana:latest
    container_name: grafana-2
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data-2:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app-network

  grafana-3:
    image: grafana/grafana:latest
    container_name: grafana-3
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data-3:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grafana-1
      - grafana-2
      - grafana-3
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data-1:
  grafana-data-2:
  grafana-data-3:
